# Nombre con el que se registrará el microservicio y puerto de arranque
spring.application.name=empresa
server.port=8082
spring.profiles.active=dev

# URL para registrarse y comunicarse con el servidor de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Credenciales y ruta para conectarse a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/empresas_db
spring.datasource.username=root
spring.datasource.password=root

# Configuración de Hibernate para actualizar las tablas y mostrar el SQL en consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Activación y rutas para la interfaz gráfica de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs