
spring.application.name=MS-CATEGORIA
server.port=8092
spring.profiles.active=dev

# URL para registrarse y comunicarse con el servidor de Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# Credenciales y ruta para conectarse a la base de datos
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/db_categoria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para actualizar las tablas
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#  rutas para la interfaz gráfica de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs